services:
  ecommerceapi:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    container_name: ecommerceapi
    build:
      context: .
      dockerfile: ECommerceApi/Dockerfile
    ports:
      - "5001:8081"
    environment:
      - ConnectionStrings__Default=Server=app-db,1433;Database=eshop;User Id=sa;Password=StrongPass1;MultipleActiveResultSets=true;TrustServerCertificate=true;
      - Jaeger__Endpoint=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      # Force sampling for testing
      - OTEL_SAMPLING_PROBABILITY=1.0
      - OTEL_TRACES_SAMPLER=always_on
    depends_on:
      jaeger:
        condition: service_started        
    networks:
      - observability

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
        - 9090:9090
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability
  
  appdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass1
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: api.jaeger    
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "14250:14250"   # Model
      - "14268:14268"   # Jaeger HTTP
      - "6831:6831/udp" # Jaeger thrift compact
      - 13133:13133 # Health Check endpoint
    environment:
        - COLLECTOR_OTLP_ENABLED=true
    networks:
      - observability
    

volumes:
  prometheus:
    
networks:
  observability:
     driver: bridge  
