@CatalogApi_HostAddress = https://localhost:7292/api/products


###
Get {{CatalogApi_HostAddress}}
Accept: application/json

###
GET {{CatalogApi_HostAddress}}/1
Accept:application/json

###
POST {{CatalogApi_HostAddress}}
Content-Type: application/json
{
    "id":0
    "name":"",
    "description":"",
    "price":59.33,
    "imageUrl":""
}

###
PUT {{CatalogApi_HostAddress}}/1
Content-Type: application/json
{
    "id":1,
    "name":"Solar Powered FlashLight",
    "description":"A fantastic Flashlight with Solar powered.",
    "price":33.99,
    "imageUrl":"https://m.media-amazon.com/images/I/61FOUArF3nL._AC_UL320_.jpg"
}

###
DELETE {{CatalogApi_HostAddress}}/10
Content-Type: application/json

###
GET {{CatalogApi_HostAddress}}/support/give-me-1-outdoor-activity
Accept: application/json

###
GET {{CatalogApi_HostAddress}}/support/what-is-microservices
Accept: application/json

###
GET {{CatalogApi_HostAddress}}/search/earbuds
Accept: application/json
###

GET {{CatalogApi_HostAddress}}/aisearch/headphone
Accept: application/json

###
GET {{CatalogApi_HostAddress}}/aisearch/wireless
Accept: application/json