@CatalogApi_HostAddress = https://localhost:7292/api/products


###
Get {{CatalogApi_HostAddress}}
Accept: application/json

###
GET {{CatalogApi_HostAddress}}/1
Accept:application/json

###
POST {{CatalogApi_HostAddress}}
Content-Type: application/json
{
    "id":0
    "name":"",
    "description":"",
    "price":59.33,
    "imageUrl":""
}