services:
  longrunningapi:
    image: ${DOCKER_REGISTRY-}longrunningapi
    build:
      context: .
      dockerfile: LongRunningApi/Dockerfile
    ports:
     - "5001:8081"
    environment:
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_TRACES_SAMPLER_ARG=1.0
    networks:
     - mynetwork
  
  postgres:
    image: postgres:17
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./.containers/db:/var/lib/postgresql/data
    ports:
        - 5432:5432
    networks:
        - mynetwork
  
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
