@BasketApi_HostAddress = https://localhost:7203/api/Basket

GET {{BasketApi_HostAddress}}/mani1
Accept: application/json

###
POST {{BasketApi_HostAddress}}
Content-Type:application/json
{
    "UserName":"mani1",
    "Items":[
        {
            "Quantity":2,
            "Color":"Red",
            "Price":0,
            "ProductId":1,
            "ProductName":"Wrong ProductName"
        },
        {
            "Quantity":1,
            "Color":"Blue",
            "Price":0,
            "ProductId":2,
            "ProductName":"Name Come from CatalogApi"
        },
        {
            "Quantity":3,
            "Color":"Blue",
            "Price":0,
            "ProductId":3,
            "ProductName":"Name Come from CatalogApi"
        }
    ]
}

###
DELETE {{BasketApi_HostAddress}}/mani

