services:
  eshop.orders:
    image: ${DOCKER_REGISTRY-}eshoporders
    container_name: eshop.orders
    build:
      context: .
      dockerfile: eshop.Orders/Dockerfile
    ports:
      - "5001:8081"
    environment:
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=eshop;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_EXPORTER=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    networks:
      - monolith

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - monolith
  
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
  
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
       RABBITMQ_DEFAULT_USER: guest
       RABBITMQ_DEFAULT_PASS: guest
    ports:
       - 5672:5672
       - 15672:15672

networks:
  monolith:
      
  
