services:
  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
    expose:
      - "8080"
    ports:
      - "4000:8080"      
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./log/productsapi:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
        - yarp

  salesapi:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: SalesApi/Dockerfile
    ports:
      - "6000:8080"
      - "6001:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./log/salessapi:/app/logs
    networks:
        - yarp


  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: UsersApi/Dockerfile
    ports:
      - "7000:8080"
      - "7001:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./log/usersapi:/app/logs
    networks:
        - yarp

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
        DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
        - 18888:18888
    networks:
        - yarp

  gatewayapi:
    image: mcr.microsoft.com/dotnet/nightly/yarp:latest      # ${DOCKER_REGISTRY-}gatewayapi
    # build:
    #   context: .
    #   dockerfile: GatewayApi/Dockerfile
    ports:
      - "5000:8080"
      # - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__Console__FormatterName=Simple
      - Logging__Console__FormatterOptions__SingleLine=true
      - DOTNET_CONSOLE_FORMATTER=Simple
    volumes:
      - ./log/gateway:/app/logs
      - ./gateway/appsettings.json:/etc/yarp.config
    networks:
      - yarp
    
 

networks:
  yarp:
    name: yarp-network
    driver: bridge


