services:
  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./log/productsapi:/app/logs
    networks:
        - yarp

  salesapi:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: SalesApi/Dockerfile
    ports:
      - "6000:8080"
      - "6001:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./log/salessapi:/app/logs
    networks:
        - yarp


  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: UsersApi/Dockerfile
    ports:
      - "7000:8080"
      - "7001:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./log/usersapi:/app/logs
    networks:
        - yarp

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
        DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
        - 18888:18888
    networks:
        - yarp

  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    ports:
      - "4000:8080"
      - "4001:8081"
    volumes:
      - ./log/gateway:/app/logs
    networks:
      - yarp

networks:
  yarp:
    driver: bridge


