services:
  lokigraf.api:
    image: ${DOCKER_REGISTRY-}lokigrafapi
    build:
      context: .
      dockerfile: LokiGraf.Api/Dockerfile
    ports:
       - "5000:8080"
       - "5001:8081"
    environment:
      loki: http://loki:3100
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080;http://+:8081
    depends_on:
        loki:
            condition: service_healthy
    networks:
      - log

  loki:
   container_name: loki
   image: grafana/loki:master
   ports:
    - "3100:3100"
   command: -config.file=/etc/loki/local-config.yaml
   healthcheck:
       test: wget -q --tries=1 -O- http://localhost:3100/ready
       interval: 3s
       timeout: 3s
       retries: 10
       start_period: 10s
   networks:
     - log
  
  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
     - "3000:3000"
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - log

networks:
  log:
     driver: bridge

