services:
  helloapi:
    image: ${DOCKER_REGISTRY-}helloapi
    build:
      context: .
      dockerfile: HelloApi/Dockerfile
    networks:
      - apigateway

  yarpproxy:
    image: ${DOCKER_REGISTRY-}yarpproxy
    build:
      context: .
      dockerfile: YarpProxy/Dockerfile
    ports:
        - "3000:8080"
    depends_on:
      - helloapi
    networks:
      - apigateway
  
  nginx:
    image: nginx:alpine
    ports:
        - "3001:80"
    volumes:
     - ./YarpProxy/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - helloapi
    networks:
      - apigateway

networks:
  apigateway:
    driver: bridge
  

