services:
  fileuploadapi:
    image: ${DOCKER_REGISTRY-}fileuploadapi
    build:
      context: .
      dockerfile: FileUploadApi/Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/Logs
      - ./appsettings.json:/app/appsettings.json
    networks:
      - default

networks:
  default:
    driver: bridge
